name: yt kids Workflow

on:
  #schedule:
  #  - cron: '31 */3 * * *'  # Runs every 4 hours
  #push:
  #  branches:
  #    - main  # Adjust the branch name as needed
  #pull_request:
  #  branches:
  #    - main  # Adjust the branch name as needed
  # Allows you to run this workflow manually from the Actions tab #
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest  # Use the latest version of Ubuntu as the runner

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2  # Checkout your repository's code
    - uses: actions/checkout@v1  
      with:
        repository: Ar-Sa/SMbot
        token: ${{ secrets.smbotpat }}

    - name: Set up Python
      uses: actions/setup-python@v2  # Set up Python on the runner
      with:
        python-version: '3.x'  # Specify the Python version (e.g., 3.6, 3.7, etc.)
    
    - name: Install ImageMagick
      run: sudo apt-get update &&  sudo apt-get install -y --install-suggests imagemagick

    
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install moviepy
        python -m pip install gtts
        #python -m pip install mutagen
        python -m pip install google
        python -m pip install google_auth_oauthlib
        python -m pip install google-api-python-client
        python -m pip install facebook-sdk 
        python -m pip install matplotlib
        python -m pip install openai
        python -m pip install Pillow

    - name: Run  Script
      run: |
          #python ytpy/video-kids.py # Replace with the name of your PyTorch script
          python -c "with open('test1.txt', 'w') as f: f.write('This is a test file.')"
          python -c "with open('ytpy/test.txt', 'w') as f: f.write('This is a test file.')"

    - name: Commit changes
      run: |
        git config --global user.email "toarun4u@gmail.com"
        git config --global user.name "gitcommit.acc"
        git pull
        git add .
        git commit -m "Auto commit - Updated content"
        git push
