name: remove AI files

on:
  schedule:
    - cron: '54 */23 * * *'  # Runs every 4 hours
  #push:
  #  branches:
  #    - main  # Adjust the branch name as needed
  #pull_request:
  #  branches:
  #    - main  # Adjust the branch name as needed
  # Allows you to run this workflow manually from the Actions tab #
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest  # Use the latest version of Ubuntu as the runner

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2  # Checkout your repository's code

    - name: Set up Python
      uses: actions/setup-python@v2  # Set up Python on the runner
      with:
        python-version: '3.x'  # Specify the Python version (e.g., 3.6, 3.7, etc.)
    

    - name: Checkout private tools
      uses: actions/checkout@v3
      with:
        repository: Ar-Sa/SMbot
        token: ${{ secrets.SMBOTPAT }} # `GH_PAT` is a secret that contains your PAT
        path: SMbot

    - name: Run  Script
      run: |
        echo "Current Working Directory: $PWD"
        ls -l | grep '^d' | awk '{print $9}'
        cd SMbot/ytpy
        ls -l | grep '^d' | awk '{print $9}'
        python old-py/remove-aifiles.py

