name: test-vd

on:
  schedule:
    - cron: '0 21 * * 2,4,6' 
  #push:
  #  branches:
  #    - main  # Adjust the branch name as needed
  #pull_request:
  #  branches:
  #    - main  # Adjust the branch name as needed
  # Allows you to run this workflow manually from the Actions tab #
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest  # Use the latest version of Ubuntu as the runner

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2  # Checkout your repository's code

    - name: Set up Python
      uses: actions/setup-python@v2  # Set up Python on the runner
      with:
        python-version: '3.x'  # Specify the Python version (e.g., 3.6, 3.7, etc.)
     
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install modelscope==1.4.2
        python -m pip install pytorch-lightning
        python -m pip install open_clip_torch==2.24.0
        


    - name: Checkout private tools
      uses: actions/checkout@v3
      with:
        repository: Ar-Sa/SMbot
        token: ${{ secrets.SMBOTPAT }} # `GH_PAT` is a secret that contains your PAT
        path: SMbot

    - name: Run  Script
      #run: python ytpy/test-vd.py # Replace with the name of your PyTorch script
      run: |
        echo "Current Working Directory: $PWD"
        ls -l | grep '^d' | awk '{print $9}'
        cd SMbot/ytpy
        ls -l | grep '^d' | awk '{print $9}'
        python test-vd.py 

    - name: Commit changes
      run: |
        echo "Current Working Directory: $PWD"
        ls -l | grep '^d' | awk '{print $9}'
        cd SMbot
        ls -l | grep '^d' | awk '{print $9}'
        git config --global user.email "toarun4u@gmail.com"
        git config --global user.name "gitcommit.acc"
        git pull
        git add .
        git commit -m "AI-kids -Auto commit"
        git push
