name: test-vd

on:
  schedule:
    - cron: '0 21 * * 2,4,6'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'  # Specify a concrete version like 3.10 or 3.11 for compatibility

    - name: Install dependencies
      run: |
          pip install --upgrade pip  # Install core dependencies
          git clone https://github.com/Ar-Sa/Text2Video-Zero.git
          cd Text2Video-Zero
          pip install -r requirements.txt
          
    - name: Checkout private tools
      uses: actions/checkout@v2
      with:
        repository: Ar-Sa/SMbot
        token: ${{ secrets.SMBOTPAT }}
        path: SMbot

    - name: Run Script
      run: |
        echo "Current Working Directory: $PWD"
        ls -l
        cd SMbot/ytpy
        ls -l
        python test-vd.py 

    - name: Commit changes
      run: |
        echo "Current Working Directory: $PWD"
        ls -l
        cd SMbot
        git config --global user.email "toarun4u@gmail.com"
        git config --global user.name "gitcommit.acc"
        git pull
        git add .
        git commit -m "AI-kids - Auto commit"
        git push --force
