name: Update YAML Files

on:
  schedule:
    - cron: '0 0 */14 * *' # Runs every 2 weeks at midnight UTC
  workflow_dispatch:

permissions:
  contents: write
  
jobs:
  update-yaml:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Update YAML files with the current date
      - name: Update YAML files
        run: |
          for file in .github/workflows/*.yml; do
            if [[ -f "$file" ]]; then
              # Append the current date as a comment
              echo -e "\n# Updated on $(date '+%Y-%m-%d')" >> "$file"
            fi
          done

      # Step 3: Commit and push changes
      - name: Commit and push changes
        run: |
          git config --global user.email "toarun4u@gmail.com"
          git config --global user.name "gitcommit.acc"
          git add .
          git commit -m "Update YAML files with current date"
          git push
