name: kids

on:
  schedule:
    - cron: '20 */6 * * *' 
  #push:
  #  branches:
  #    - main  # Adjust the branch name as needed
  #pull_request:
  #  branches:
  #    - main  # Adjust the branch name as needed
  # Allows you to run this workflow manually from the Actions tab #
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest  # Use the latest version of Ubuntu as the runner

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2  # Checkout your repository's code

    - name: Set up Python
      uses: actions/setup-python@v2  # Set up Python on the runner
      with:
        python-version: '3.x'  # Specify the Python version (e.g., 3.6, 3.7, etc.)
    
    - name: Install ImageMagick
      run: sudo apt-get update &&  sudo apt-get install -y --install-suggests imagemagick

    #- name: Install ImageMagick2
    ## ImageMagicK Installation 
    #  run: mkdir -p /tmp/distr && cd /tmp/distr && wget https://download.imagemagick.org/archive/releases/ImageMagick-7.1.1-25.tar.xz && tar xvf ImageMagick-7.1.1-25.tar.xz && cd ImageMagick-7.1.1-25 && ./configure --enable-shared=yes --disable-static --without-perl &&  make && sudo make install && sudo ldconfig /usr/local/lib
    - name: Install ImageMagick1
      run:  |
        #sudo apt-get install libmagick++-dev
        cat "/etc/ImageMagick-6/policy.xml"
        sudo cp -f .github/policy.xml /etc/ImageMagick-6/policy.xml
        cat "/etc/ImageMagick-6/policy.xml"
        mkdir -p ~/.fonts
        cp .github/NotoSansDevanagari-Regular.ttf ~/.fonts/
        fc-cache -fv
    
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install moviepy==1.0.3
        python -m pip install langdetect
        python -m pip install gtts
        #python -m pip install mutagen
        python -m pip install google
        python -m pip install google_auth_oauthlib
        python -m pip install google-api-python-client
        python -m pip install facebook-sdk 
        python -m pip install matplotlib
        python -m pip install openai
        python -m pip install Pillow
        python -m pip install azure-cognitiveservices-speech


    - name: Checkout private tools
      uses: actions/checkout@v3
      with:
        repository: Ar-Sa/SMbot
        token: ${{ secrets.SMBOTPAT }} # `GH_PAT` is a secret that contains your PAT
        path: SMbot

    - name: Run  Script
      #run: python ytpy/test.py # Replace with the name of your PyTorch script
      run: |
        echo "Current Working Directory: $PWD"
        ls -l | grep '^d' | awk '{print $9}'
        cd SMbot/ytpy
        ls -l | grep '^d' | awk '{print $9}'
        python video-kids.py 

    - name: Commit changes
      run: |
        echo "Current Working Directory: $PWD"
        ls -l | grep '^d' | awk '{print $9}'
        cd SMbot
        ls -l | grep '^d' | awk '{print $9}'
        git config --global user.email "toarun4u@gmail.com"
        git config --global user.name "gitcommit.acc"
        git pull
        git add .
        git commit -m "AI-kids -Auto commit"
        git push

